import {useEffect,useRef,useState,lazy,Suspense} from 'react';
import {createRoot} from 'react-dom/client';
import {AudioLines,ArrowUp,ArrowUpRight,Bookmark,Check,ChevronRight,Download,Headphones,MapPin,Mic,MicOff,Search,Settings2,SlidersHorizontal,Users,Video,X} from 'lucide-react';
import {api,type Candidate,type Brief,type Message,type Interview,type ToolEvent} from './types';
import {useVoice} from './useVoice';
import './styles.css';
const InterviewRoom=lazy(()=>import('./InterviewRoom'));
const blankBrief:Brief={idea:'',strengths:'',lookingFor:'',constraints:''};
const initial:Message={role:'assistant',content:'Hi, ich bin Voya. Lass uns jemanden finden, mit dem du wirklich etwas aufbauen willst.\n\nWas möchtest du gründen – und welche Stärke soll dein Co-Founder mitbringen, die dir selbst noch fehlt?'};
function readLocal<T>(key:string,fallback:T):T{try{const value=localStorage.getItem(key);return value?JSON.parse(value):fallback;}catch{return fallback;}}
function saveLocal(key:string,value:unknown){try{localStorage.setItem(key,JSON.stringify(value));}catch{/* The workspace remains usable when storage is unavailable. */}}
function download(name:string,content:string){const url=URL.createObjectURL(new Blob([content],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const pretty=(s:string)=>s.replaceAll('-',' ');
const initials=(s:string)=>s.split(' ').slice(0,2).map(w=>w[0]).join('');
function Avatar({candidate,large=false}:{candidate:Candidate;large?:boolean}){
  const [imageIndex,setImageIndex]=useState(0);
  const images=candidate.avatars||[];
  useEffect(()=>setImageIndex(0),[candidate.id,images.join('|')]);
  return <div className={`avatar ${large?'large':''}`} style={{'--hue':String([...candidate.id].reduce((n,c)=>n+c.charCodeAt(0),0)%260)} as React.CSSProperties}>
    {images[imageIndex]?<img src={images[imageIndex]} alt={`Profilbild von ${candidate.name}`} loading={large?'eager':'lazy'} decoding="async" referrerPolicy="no-referrer" onError={()=>setImageIndex(index=>index+1)}/>:initials(candidate.name)}
  </div>;
}
function App(){
  const [candidates,setCandidates]=useState<Candidate[]>([]),[status,setStatus]=useState<{total:number;linkedin:number;enriched:number;ai:boolean;room:boolean}|null>(null);
  const [query,setQuery]=useState(''),[linkedOnly,setLinkedOnly]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState('');
  const [tab,setTab]=useState<'all'|'saved'>('all');
  const [saved,setSaved]=useState<string[]>(()=>readLocal('tandem.saved',[]));
  const [brief,setBrief]=useState<Brief>(()=>readLocal('tandem.brief',blankBrief));
  const [messages,setMessages]=useState<Message[]>([initial]),[draft,setDraft]=useState(''),[busy,setBusy]=useState(false);
  const [modal,setModal]=useState<'settings'|'brief'|'room'|null>(null),[interview,setInterview]=useState<Interview|null>(null);
  const [focused,setFocused]=useState<Candidate|null>(null);
  function focusCandidate(p:Candidate){setFocused(p);}
  const [activity,setActivity]=useState(''),[visibleCount,setVisibleCount]=useState(30);
  const bottom=useRef<HTMLDivElement>(null);
  function applyEvent(event:ToolEvent){const r=event.result;if(r.query!==undefined){setQuery(r.query);setTab('all');setActivity(`Profile nach „${r.query}“ durchsucht`);}if(r.candidate){focusCandidate(r.candidate);setActivity(`Lebenslauf von ${r.candidate.name} gelesen`);}if(r.brief){setBrief(r.brief);setActivity('Suchprofil aktualisiert');}if(r.interview){setInterview(r.interview);setActivity('Interviewleitfaden vorbereitet');}}
  const voice=useVoice(m=>setMessages(prev=>[...prev,m]),applyEvent,setError,focused);
  useEffect(()=>{api<typeof status>('/api/status').then(setStatus).catch(e=>setError(e.message));},[]);
  useEffect(()=>{let active=true;setLoading(true);const timer=setTimeout(()=>{api<{candidates:Candidate[]}>(`/api/candidates?q=${encodeURIComponent(query)}&linkedin=${linkedOnly}`).then(r=>{if(active){setCandidates(r.candidates);setVisibleCount(30);}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});},180);return()=>{active=false;clearTimeout(timer);};},[query,linkedOnly]);
  useEffect(()=>saveLocal('tandem.saved',saved),[saved]);useEffect(()=>saveLocal('tandem.brief',brief),[brief]);
  useEffect(()=>{const list=bottom.current?.parentElement;if(list)list.scrollTop=list.scrollHeight;},[messages,busy]);
  function toggleSaved(id:string){setSaved(prev=>prev.includes(id)?prev.filter(x=>x!==id):[...prev,id]);}
  async function send(text=draft){if(!text.trim()||busy||voice.state!=='idle')return;if(!status?.ai){setModal('settings');return;}const next:Message[]=[...messages,{role:'user',content:text.trim()}];setMessages(next);setDraft('');setBusy(true);setError('');try{const reply=await api<{text:string;events:ToolEvent[]}>('/api/agent',{messages:next.slice(-60),brief:{...brief,currentCandidate:focused?{id:focused.id,name:focused.name}:null}});reply.events.forEach(applyEvent);setMessages([...next,{role:'assistant',content:reply.text}]);}catch(e){setError((e as Error).message);setDraft(text);setMessages(next.slice(0,-1));}finally{setBusy(false);}}
  function exportInterview(){if(!interview)return;download('cofounder-interview.md',`# ${interview.title}\n\n${interview.duration}\n\n${interview.sections.map(s=>`## ${s.title} (${s.minutes} Min.)\n\n${s.questions.map(q=>`- ${q}`).join('\n')}`).join('\n\n')}\n\n## Offene Punkte\n${interview.unknowns.map(x=>`- ${x}`).join('\n')}`);}
  useEffect(()=>{
    if(!modal)return;
    const previous=document.activeElement as HTMLElement|null;
    const dialog=document.querySelector<HTMLElement>('.modal');
    const oldOverflow=document.body.style.overflow;document.body.style.overflow='hidden';
    const focusable=()=>Array.from(dialog?.querySelectorAll<HTMLElement>('button:not(:disabled), a[href], input, textarea, [tabindex="0"]')||[]);
    focusable()[0]?.focus();
    const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();setModal(null);}if(e.key==='Tab'){const nodes=focusable(),first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};
    document.addEventListener('keydown',onKey);return()=>{document.removeEventListener('keydown',onKey);document.body.style.overflow=oldOverflow;previous?.focus();};
  },[modal]);
  const filtered=candidates.filter(p=>tab==='all'||saved.includes(p.id));
  const completion=Object.values(brief).filter(Boolean).length;
  return <div className="app">
    <header className="topbar"><a className="brand" href="/" aria-label="Voya Startseite"><span className="brandmark"><i/><i/></span>voya<span className="brand-note">Co-Founder Studio</span></a><div className="top-actions"><span className="local-label"><span/>Dein privater Workspace</span><button className="icon-button" aria-label="Verbindungen und Einrichtung" onClick={()=>setModal('settings')}><Settings2 size={19}/></button><span className="user-avatar">R</span></div></header>
    <main className="workspace">
      <aside className={`conversation ${focused||voice.state!=='idle'?'compact-conversation':''}`}>
        <div className="conversation-heading"><div className="agent-icon"><AudioLines size={23}/></div><div><h2>Dein Sparringspartner</h2><p><span className={`status-dot ${status?.ai?'online':''}`}/>{status?.ai?'Bereit für eure nächste Idee':'KI-Verbindung einrichten'}</p></div><button className="icon-button" title="Gespräch exportieren" aria-label="Gespräch exportieren" onClick={()=>download('voya-gespraech.md',messages.map(m=>`## ${m.role==='user'?'Du':'Voya'}\n\n${m.content}`).join('\n\n'))}><Download size={17}/></button></div>
        <div className="voice-stage"><div className={`voice-art ${voice.state!=='idle'?'active':''}`} aria-hidden="true"><div className="ribbon r1"/><div className="ribbon r2"/><div className="ribbon r3"/><div className="ribbon r4"/><div className="ribbon r5"/></div><h1>Gute Teams beginnen<br/>mit einem Gespräch.</h1><p>Erzähl von deiner Idee.<br/>Wir finden heraus, wer sie mit dir groß macht.</p><button className={`voice-button ${voice.state!=='idle'?'connected':''}`} disabled={busy} onClick={()=>{if(voice.state!=='idle')voice.stop();else if(!status?.ai)setModal('settings');else void voice.start(brief,messages);}}>{voice.state==='idle'?<Mic size={17}/>:<Headphones size={17}/>} {voice.state==='idle'?'Gespräch starten':voice.state==='connecting'?'Verbindung abbrechen':'Gespräch beenden'}</button>{voice.state!=='idle'&&<div className="voice-status"><span>{voice.state==='connecting'?'Verbindung wird aufgebaut …':voice.muted?'Mikrofon stumm':voice.state==='speaking'?'Voya spricht':'Voya hört zu'}</span><button className="icon-button" onClick={voice.toggleMute} aria-label={voice.muted?'Mikrofon einschalten':'Mikrofon stummschalten'}>{voice.muted?<MicOff size={16}/>:<Mic size={16}/>}</button></div>}<small>Mit KI sprechen · Du kannst jederzeit unterbrechen</small></div>
        <div className="chat-label"><span>Unser Gespräch</span><span>{messages.length>1?`${messages.length} Beiträge`:'Ein guter Anfang'}</span></div>
        <div className="messages" aria-live="polite">{messages.map((m,i)=><div className={`message ${m.role}`} key={i}><span className="message-author">{m.role==='user'?'Du':'Voya'}</span><p>{m.content}</p></div>)}{busy&&<div className="working"><span className="status-dot online"/>Voya denkt nach und prüft Profile …</div>}<div ref={bottom}/></div>
        {focused&&<section className="embedded-profile" aria-label="Kandidat im Gespräch">
          <div className="embedded-profile-heading"><Avatar candidate={focused}/><div><span>Gerade im Gespräch</span><h3>{focused.name}</h3><p title={focused.headline}>{focused.headline||'Berufliche Angaben noch offen'}</p></div><button className="icon-button" aria-label="Gesprächsprofil ausblenden" onClick={()=>setFocused(null)}><X size={15}/></button></div>
          {focused.experience.length?<ul className="embedded-experience">{focused.experience.slice(0,2).map((e,i)=><li key={i} title={[e.title,e.company].filter(Boolean).join(' · ')}><strong>{e.title||'Position offen'}</strong>{e.company&&<span> · {e.company}</span>}</li>)}</ul>:<p className="embedded-empty">Keine beruflichen Stationen hinterlegt.</p>}
          <div className="embedded-profile-actions">{focused.linkedin?<a href={focused.linkedin} target="_blank" rel="noreferrer">LinkedIn-Profil <ArrowUpRight size={13}/></a>:<span>Kein LinkedIn-Link vorhanden</span>}<button aria-label={`${focused.name} ${saved.includes(focused.id)?'aus Merkliste entfernen':'merken'}`} onClick={()=>toggleSaved(focused.id)}><Bookmark size={13} fill={saved.includes(focused.id)?'currentColor':'none'}/>{saved.includes(focused.id)?'Gemerkt':'Merken'}</button>{interview?.candidateId===focused.id&&<button onClick={exportInterview}><Download size={13}/>Leitfaden</button>}</div>
        </section>}
        {activity&&<div className="activity"><Check size={13}/>{activity}</div>}
        <form className="composer" onSubmit={e=>{e.preventDefault();void send();}}><label className="sr-only" htmlFor="message">Nachricht an Voya</label><textarea id="message" placeholder="Oder schreib mir deine Gedanken …" value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void send();}}}/><button aria-label="Nachricht senden" disabled={busy||!draft.trim()||voice.state!=='idle'}><ArrowUp size={19}/></button></form>
        <p className="chat-footnote">{status?.ai?'KI kann sich irren. Prüfe wichtige Angaben im Profil.':'Profile lokal erkunden. KI-Dialog nach Einrichtung verfügbar.'}</p>
      </aside>
      <section className="discovery">
        <div className="discovery-head"><div><div className="breadcrumb">Dein nächstes Kapitel <ChevronRight size={12}/> Das passende Team</div><h2>Zusammen mehr bewegen.</h2><p>Entdecke die Menschen hinter den Lebensläufen.</p></div><button className="secondary room-button" onClick={()=>{voice.stop();setModal('room');}}><Video size={16}/>Interviewraum</button></div>
        <button className="brief-summary" onClick={()=>setModal('brief')}><div className="brief-symbol"><SlidersHorizontal size={20}/></div><div><strong>{brief.lookingFor||'Wen möchtest du an deiner Seite?'}</strong><span>{brief.idea||'Schärfe mit Voya dein Suchprofil – oder ergänze es selbst.'}</span></div><span className="brief-progress">{completion}/4 geklärt</span><ChevronRight size={17}/></button>
        <div className="list-toolbar"><div className="tabs"><button className={tab==='all'?'selected':''} onClick={()=>setTab('all')}>Entdecken <span>{status?.total??'–'}</span></button><button className={tab==='saved'?'selected':''} onClick={()=>setTab('saved')}>Merkliste <span>{saved.length}</span></button></div><span className="source-label">Aus deinem IdeaLab-Netzwerk</span></div>
        <div className="search-row"><div className="search-box"><Search size={18}/><input aria-label="Kandidaten durchsuchen" placeholder="Name, Erfahrung, Unternehmen oder Skill" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button className="icon-button" onClick={()=>setQuery('')} aria-label="Suche löschen"><X size={15}/></button>}</div><button className={`filter ${linkedOnly?'active':''}`} onClick={()=>setLinkedOnly(!linkedOnly)} aria-pressed={linkedOnly}><span className="linkedin-icon">in</span>LinkedIn{linkedOnly&&<Check size={13}/>}</button></div>
        <div className="results-caption"><span>{loading?'Profile werden geladen …':`${filtered.length} Profile${query?' gefunden':''}`}</span><span>Berufliche Erfahrung. Echte Anknüpfungspunkte.</span></div>
        <div className="candidate-list">{!loading&&!filtered.length&&<div className="empty"><Users size={32}/><h3>{tab==='saved'?'Deine Merkliste beginnt hier.':'Noch kein passendes Profil gefunden.'}</h3><p>{tab==='saved'?'Markiere interessante Personen mit dem Lesezeichen.':'Versuche andere Begriffe oder entferne den LinkedIn-Filter.'}</p><button className="secondary" onClick={()=>{setTab('all');setQuery('');setLinkedOnly(false);}}>Alle Profile entdecken</button></div>}{filtered.slice(0,visibleCount).map((p,i)=><article key={p.id} className={`candidate ${focused?.id===p.id?'chosen':''}`}><button className="candidate-main" onClick={()=>focusCandidate(p)}><Avatar candidate={p}/><div className="candidate-info"><div className="candidate-name"><h3>{p.name}</h3>{p.linkedin&&<span className="linkedin-icon">in</span>}</div><p className="headline">{p.headline||'Berufliche Angaben noch offen'}</p><div className="candidate-meta">{p.location?<span><MapPin size={12}/>{p.location}</span>:<span>Standort nicht angegeben</span>}<span className="source-pill">{p.source}</span></div><div className="tags">{(p.skills.length?p.skills:p.interests).slice(0,3).map((s,j)=><span key={j}>{pretty(s)}</span>)}{p.matches?.length?<span className="match-tag">{p.matches.length} Suchtreffer</span>:null}</div></div><ChevronRight className="candidate-chevron" size={18}/></button><button className={`save-button ${saved.includes(p.id)?'saved':''}`} aria-label={`${p.name} ${saved.includes(p.id)?'aus Merkliste entfernen':'merken'}`} aria-pressed={saved.includes(p.id)} onClick={()=>toggleSaved(p.id)}><Bookmark size={18} fill={saved.includes(p.id)?'currentColor':'none'}/></button><span className="candidate-index">{String(i+1).padStart(2,'0')}</span></article>)}{visibleCount<filtered.length&&<button className="load-more secondary" onClick={()=>setVisibleCount(n=>n+30)}>Weitere Profile anzeigen</button>}</div>
        <footer className="data-note"><span><span className="status-dot online"/>{status?.enriched??'–'} Profile mit LinkedIn-Lebenslauf</span><span>Verfügbarkeit und Gründungsinteresse gemeinsam klären.</span></footer>
      </section>
    </main>
    {error&&<div className="error-toast" role="alert"><span>{error}</span><button className="icon-button" aria-label="Fehlermeldung schließen" onClick={()=>setError('')}><X size={17}/></button></div>}
    {modal&&<div className="modal-backdrop" onClick={()=>setModal(null)}><section className={`modal ${modal==='room'?'room-modal':''}`} role="dialog" aria-modal="true" aria-label={modal==='brief'?'Dein Suchprofil':modal==='room'?'Interviewraum':'Verbindungen'} onClick={e=>e.stopPropagation()}><button autoFocus className="modal-close icon-button" aria-label="Dialog schließen" onClick={()=>setModal(null)}><X size={22}/></button>{modal==='brief'?<><div className="agent-icon"><SlidersHorizontal/></div><h2>Dein Team beginnt bei dir.</h2><p>Was du hier festhältst, gibt Voya Orientierung. Deine Angaben werden in diesem Browser gespeichert.</p><form onSubmit={e=>{e.preventDefault();setModal(null);}}>{([['idea','Deine Idee','Welches Problem möchtest du für wen lösen?'],['strengths','Was du mitbringst','Deine Stärken, Erfahrung und bisheriger Fortschritt'],['lookingFor','Die gesuchte Ergänzung','Welche Fähigkeiten fehlen dir?'],['constraints','Was passen muss','Standort, Zeit, Starttermin und Rahmenbedingungen']] as const).map(([key,label,placeholder])=><label className="field" key={key}>{label}<textarea value={brief[key]} placeholder={placeholder} onChange={e=>setBrief({...brief,[key]:e.target.value})}/></label>)}<button className="primary full">Suchprofil übernehmen</button></form></>:modal==='room'?<><h2>Dein Interviewraum</h2><p>Mit Cloudflare RealtimeKit. Kamera und Mikrofon startest du selbst.</p><Suspense fallback={<p>Gesprächskomponenten werden geladen …</p>}><InterviewRoom/></Suspense></>:<><div className="agent-icon"><Settings2/></div><h2>Verbindungen</h2><p>Deine Profile sind bereits da. Für Gespräche verbindest du die KI mit deinem lokalen Workspace.</p><div className="connection-row"><div><strong>IdeaLab & LinkedIn</strong><p>{status?.total??0} Profile · {status?.enriched??0} angereicherte Lebensläufe</p></div><span className="source-pill">Lokal</span></div><div className="connection-row"><div><strong>KI-Dialog & Sprache</strong><p>OpenAI Realtime und Text-Agent</p></div><span className="source-pill">{status?.ai?'Verbunden':'Nicht eingerichtet'}</span></div>{!status?.ai&&<div className="setup-note">Trage <code>OPENAI_API_KEY</code> in <code>/Users/rene/github.com/RocketRene/openai-hackathon/web/.env</code> ein und starte den lokalen Server neu. Der Schlüssel bleibt auf dem Server. Beim Gespräch werden deine Eingaben und vom Agenten abgerufene Profile an OpenAI übermittelt.</div>}<div className="connection-row"><div><strong>Interviewraum</strong><p>Cloudflare RealtimeKit</p></div><span className="source-pill">{status?.room?'Konfiguriert':'Optional'}</span></div><p className="setup-note">Für den Raum: <code>REALTIMEKIT_AUTH_TOKEN</code> in derselben Datei setzen. Pro Teilnehmer ist ein eigener Token erforderlich. Der KI-Sprachagent läuft separat über OpenAI.</p><button className="secondary full" onClick={()=>setModal(null)}>Zurück zu den Kandidaten</button></>}</section></div>}
  </div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
